<?php

/**
 * @file
 * Contains atomos.module.
 */
use Drupal\Core\Render\Element;
use Drupal\Core\Render\Element\RenderElement;

/**
 * Implements hook_theme().
 */
function atomos_theme($existing, $type, $theme, $path) {
  return [
    'help_text_atomic' => [
      'render element' => 'element',
      'path' => drupal_get_path('module','atomos') . '/templates/form',
    ],
    'textfield_atomic' => [
      'render element' => 'element',
      'path' => drupal_get_path('module','atomos') . '/templates/form',
    ],
    'form_element_atomic' => [
      'render element' => 'element',
      'path' => drupal_get_path('module','atomos') . '/templates/form',
    ],
    'form_element_label_atomic' => [
      'render element' => 'element',
      'path' => drupal_get_path('module','atomos') . '/templates/form',
    ],
    'switch_atomic' => [
      'render element' => 'element',
    ],
  ];
}

/**
 * Prepares variables for form label templates.
 *
 * Default template: help-text-atomic.html.twig.
 */
function template_preprocess_help_text_atomic(&$variables) {
  $element = $variables['element'];
  if (isset($element['#title']) && !empty((string) $element['#title'])) {
    $variables['title'] = $element['#title'];
  }
}

/**
 * Prepares variables for input templates.
 *
 * Default template: textfield-atomic.html.twig.
 *
 */
function template_preprocess_textfield_atomic(&$variables) {
  template_preprocess_input($variables);
}

/**
 * Prepares variables for form label templates.
 *
 * Default template: form-element-atomic.html.twig.
 */
function template_preprocess_form_element_atomic(&$variables) {
  template_preprocess_form_element($variables);
  $element = &$variables['element'];
  if (isset($element['#help_text'])) {
    if (empty((string) $element['#help_text'])) {
      unset($variables['element']['#help_text']);
    } else {
      $variables['help_text'] = [
        '#type' => 'help_text_atomic',
        '#title' => $element['#help_text'],
      ];
    }
  }
  if (isset($variables['label']['#theme'])) {
    $variables['label']['#theme'] = 'form_element_label_atomic';
  }
}

/**
 * Prepares variables for form label templates.
 *
 * Default template: label-atomic.html.twig.
 */
function template_preprocess_form_element_label_atomic(&$variables) {
  template_preprocess_form_element_label($variables);
}

/**
 * Prepares variables for form label templates.
 *
 * Default template: switch-atomic.html.twig.
 */
function template_preprocess_switch_atomic(&$variables) {
  $element = $variables['element'];
  if (isset($element['#message']) && !empty((string) $element['#message'])) {
    $variables['message'] = $element['#message'];
  } else {
    $variables['message'] = t('Slide to continue.');
  }
}
